apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-demo
  labels:
    app: websocket-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: websocket-demo
  template:
    metadata:
      labels:
        app: websocket-demo
    spec:
      containers:
      - name: websocket-demo
        image: websocket-demo:latest
        ports:
        - containerPort: 80
