apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocketdemo
  labels:
    app: websocketdemo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: websocketdemo
  template:
    metadata:
      labels:
        app: websocketdemo
    spec:
      containers:
      - name: websocketdemo
        image: websocketdemo:1.0.0
        ports:
        - containerPort: 80
