apiVersion: apps/v1
kind: Deployment
metadata:
  name: rediscaller 
  labels:
    app: rediscaller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rediscaller
  template:
    metadata:
      labels:
        app: rediscaller
    spec:
      hostname: rediscaller
      subdomain: default-subdomain
      imagePullSecrets:
      - name: dockerlogin
      containers:
      - name: rediscaller
        image: kulkarniadwait44/rediscaller:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
        env: 
        - name: redis.host
          value: http://redis-svc
        - name: redis.port
          value: "6379"
        - name: server.port
          value: "8085"            
---
apiVersion: v1
kind: Service
metadata:
  name: rediscaller-svc
spec:
  type: NodePort
  selector:
    app: rediscaller
  ports:
  - name: default
    protocol: TCP
    port: 8085
    targetPort: 8085
