kind: Deployment
apiVersion: apps/v1
metadata:
  name: spring-boot-app-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-app-demo
  template:
    metadata:
      labels:
        app: spring-boot-app-demo
    spec:
      containers:
        - name: spring-boot-app
          image: localhost:8085/spring-boot-app-demo
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8085
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8085
            initialDelaySeconds: 5
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: spring-boot-app
spec:
  type: NodePort
  ports:
    - port: 8085
      targetPort: 8085
      protocol: TCP
      nodePort: 31000
  selector:
    app: spring-boot-app-demo
