apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
data:
  db_host: mongodb-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo 
  labels:
    app: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      hostname: busybox-1
      subdomain: default-subdomain
      containers:
      - name: demo
        image: kulkarniadwait44/demo:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
        env: 
        - name: APPLICATION_PROPERTIES_HOSTNAME
          valueFrom: 
            configMapKeyRef:
              name: mongodb-configmap
              key: db_host
