apiVersion: v1
kind: Service
metadata:
  labels:
      name: demo-service
      app: demo
spec:
  selector:
    app: demo
  ports:
    - name: default
      protocol: TCP
      port: 85
      targetPort: 8085
