apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-caller
  labels:
    app: demo-caller
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-caller
  template:
    metadata:
      labels:
        app: demo-caller
    spec:
      containers:
      - name: demo-caller
        image: demo-caller:1.0.0
        ports:
        - containerPort: 86