apiVersion: v1
kind: Service
metadata:
  name: demo-caller-service
spec:
  type: NodePort
  selector:
    app: demo-caller
  ports:
  - name: default
    protocol: TCP
    port: 8086
    targetPort: 8086
